version: '3'
services:
  # Base configurations
  mqtt-broker:
    image: eclipse-mosquitto:1.5.9
    container_name: unify-mqtt-broker
    volumes:
      - ./mosquitto-config:/mosquitto/config/
    ports:
      - '1883:1883'
    command: mosquitto
    networks:
      - mqtt-network
    restart: unless-stopped

  unify-base:
    image: unify-runtime:latest
    build:
      context: .
      args:
        - DEBIAN_PACKAGES
    entrypoint: /bin/true

  # Developer applications
  unify-dev-gui-server:
    image: unify-runtime
    container_name: unify-dev-gui-server
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
      - unify-dev-gui-api
    networks:
      - mqtt-network
    entrypoint: dev-gui-client --REACT_APP_MQTT_HOST mqtt-broker
    ports:
      - "3080:3080"

  unify-dev-gui-api:
    image: unify-runtime
    container_name: unify-dev-gui-api
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: dev-gui-api
    ports:
      - "1337:1337"

  # Application services
  unify-gms:
    image: unify-runtime
    container_name: unify-gms
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: uic-gms --mqtt.host mqtt-broker --mqtt.client_id gms-portable_runtime
    volumes:
      - unify_gms:/var/lib

  unify-upvl:
    image: unify-runtime
    container_name: unify-upvl
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: uic-upvl --mqtt.host mqtt-broker --mqtt.client_id upvl-portable_runtime
    volumes:
      - unify_upvl:/var/lib

  unify-nal:
    image: unify-runtime
    container_name: unify-nal
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: uic-nal --mqtt.host mqtt-broker --mqtt.client_id nal-portable_runtime
    volumes:
      - unify_nal:/var/lib

  unify-image-provider:
    image: unify-runtime
    container_name: unify-image-provider
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: uic-image-provider --mqtt.host mqtt-broker --mqtt.client_id image-provider-portable_runtime
    volumes:
      - unify_image_provider:/var/lib

  unify-upti-cap:
    image: unify-runtime
    container_name: unify-upti-cap
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    entrypoint: uic-upti-cap --mqtt.host mqtt-broker --mqtt.client_id upti-cap-portable_runtime
    volumes:
      - unify_upti_cap:/var/lib

  # Protocol controllers
  unify-zpc:
    image: unify-runtime
    container_name: unify-zpc
    restart: on-failure
    depends_on:
      - unify-base
      - mqtt-broker
    networks:
      - mqtt-network
    environment:
      - ZPC_DEVICE_TTY
      - ZPC_DEVICE_IP
      - ZPC_CONFIG_ARGS
    devices:
      - "${ZPC_DEVICE_TTY:-/dev/null}:${ZPC_DEVICE_TTY:-/dev/null}"
    entrypoint: "/unify/run_zpc.sh --mqtt.host mqtt-broker ${ZPC_CONFIG_ARGS} --mqtt.client_id zpc-portable_runtime"
    volumes:
      - unify_zpc:/var/lib

volumes:
  unify_gms:
  unify_upvl:
  unify_nal:
  unify_image_provider:
  unify_upti_cap:
  unify_zpc:


networks:
  mqtt-network:
    driver: bridge
